/// Flutter icons TabIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TabIcons
///      fonts:
///       - asset: fonts/TabIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class TabIcons {
  TabIcons._();

  static const _kFontFam = 'TabIcons';
  static const String? _kFontPkg = null;

  static const IconData summons =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tasks =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData read =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData social =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
