name: bible_quest
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  get_storage: ^2.0.2
  percent_indicator: ^3.0.1
  intl: ^0.17.0
  spring: ^2.0.2
  cloud_firestore: ^1.0.0
  firebase_auth: ^1.0.0
  cupertino_icons: ^1.0.2
  get: 4.3.8
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter
  device_preview: ^0.7.4

flutter: 
  assets: 
    - assets/images/backgrounds/
    - assets/images/sprites/arm/
    - assets/images/sprites/base/
    - assets/images/sprites/body/
    - assets/images/sprites/head/
    - assets/images/sprites/miscellaneous/
  fonts: 
    - family: TabIcons
      fonts: 
        - asset: assets/fonts/TabIcons.ttf
    - family: ReadPageIcons
      fonts: 
        - asset: assets/fonts/ReadPageIcons.ttf
    - family: Noto
      fonts: 
        - asset: assets/fonts/NotoColorEmoji.ttf
    - family: sk_Modernist
      fonts: 
        - asset: assets/fonts/sk_Modernist/Sk-Modernist-Regular.otf
        - asset: assets/fonts/sk_Modernist/Sk-Modernist-Mono.otf
        - asset: assets/fonts/sk_Modernist/Sk-Modernist-Bold.otf
  uses-material-design: true

